# Generated by Django 5.1.6 on 2026-02-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=64)),
                ("target_model", models.CharField(max_length=128)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(fields=["created_at"], name="common_admi_created_b5ce32_idx"),
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(fields=["action"], name="common_admi_action_5f6d1a_idx"),
        ),
        migrations.AddIndex(
            model_name="adminactionaudit",
            index=models.Index(fields=["target_model", "target_id"], name="common_admi_target__e61ce0_idx"),
        ),
    ]
