# Generated by Django 5.1.6 on 2026-02-17 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_crews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skatespot',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skatevideo',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skate_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skatevideo',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='skate.crew'),
        ),
        migrations.AddField(
            model_name='skatevideo',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='skate.skatespot'),
        ),
        migrations.AlterUniqueTogether(
            name='skatespot',
            unique_together={('name', 'city', 'country')},
        ),
    ]
